// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPDW0ZGu_Xi_zfVagu_sEs-iDWe-J_VE',
    appId: '1:755288942596:web:3323dda86b1fe852ddad51',
    messagingSenderId: '755288942596',
    projectId: 'phone-zone-614f2',
    authDomain: 'phone-zone-614f2.firebaseapp.com',
    storageBucket: 'phone-zone-614f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwaD6HbgVE5wdFfdAxc54agtIAKA4G8w',
    appId: '1:755288942596:android:c19a88b0f2ddc49eddad51',
    messagingSenderId: '755288942596',
    projectId: 'phone-zone-614f2',
    storageBucket: 'phone-zone-614f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgvSDiSEMB_-hLppT_se6HWyUI9xITDkI',
    appId: '1:755288942596:ios:50965c2948137827ddad51',
    messagingSenderId: '755288942596',
    projectId: 'phone-zone-614f2',
    storageBucket: 'phone-zone-614f2.firebasestorage.app',
    androidClientId: '755288942596-a0f06ai5n43n429lfabvh2j0c5g8s1dh.apps.googleusercontent.com',
    iosClientId: '755288942596-d9r3alnd5pb9hp2rqm61mdojs174ir99.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabatyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgvSDiSEMB_-hLppT_se6HWyUI9xITDkI',
    appId: '1:755288942596:ios:50965c2948137827ddad51',
    messagingSenderId: '755288942596',
    projectId: 'phone-zone-614f2',
    storageBucket: 'phone-zone-614f2.firebasestorage.app',
    androidClientId: '755288942596-a0f06ai5n43n429lfabvh2j0c5g8s1dh.apps.googleusercontent.com',
    iosClientId: '755288942596-d9r3alnd5pb9hp2rqm61mdojs174ir99.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabatyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXUUW4H_7ymSA1736m9nSd7BPTHXxeU0',
    appId: '1:755288942596:web:7fc6ce3b53ef7859ddad51',
    messagingSenderId: '755288942596',
    projectId: 'phone-zone-614f2',
    authDomain: 'phone-zone-614f2.firebaseapp.com',
    storageBucket: 'phone-zone-614f2.firebasestorage.app',
  );
}
