// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UocUU60ed8Xg-IDcZZLsW6kOEpnltog',
    appId: '1:519077558183:web:0ff2295505ee01afe96882',
    messagingSenderId: '519077558183',
    projectId: 'talabaty-f5e19',
    authDomain: 'talabaty-f5e19.firebaseapp.com',
    storageBucket: 'talabaty-f5e19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluNqfVuMlWORUJr1s0005-hTvZpTcLyw',
    appId: '1:519077558183:android:70e081b5366bc3b2e96882',
    messagingSenderId: '519077558183',
    projectId: 'talabaty-f5e19',
    storageBucket: 'talabaty-f5e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsRGMkt5oqmpuWJqYeGcPgnzVVKwiE254',
    appId: '1:519077558183:ios:432dc350cb26c74fe96882',
    messagingSenderId: '519077558183',
    projectId: 'talabaty-f5e19',
    storageBucket: 'talabaty-f5e19.firebasestorage.app',
    iosClientId: '519077558183-5au1i3365tvud563nchcjqdcmn6e4tjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabatyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsRGMkt5oqmpuWJqYeGcPgnzVVKwiE254',
    appId: '1:519077558183:ios:432dc350cb26c74fe96882',
    messagingSenderId: '519077558183',
    projectId: 'talabaty-f5e19',
    storageBucket: 'talabaty-f5e19.firebasestorage.app',
    iosClientId: '519077558183-5au1i3365tvud563nchcjqdcmn6e4tjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabatyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UocUU60ed8Xg-IDcZZLsW6kOEpnltog',
    appId: '1:519077558183:web:3db581ae9c1cb6e4e96882',
    messagingSenderId: '519077558183',
    projectId: 'talabaty-f5e19',
    authDomain: 'talabaty-f5e19.firebaseapp.com',
    storageBucket: 'talabaty-f5e19.firebasestorage.app',
  );
}
